# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.5.2"

# Copy files into place
$setupscript = <<END
echo "192.168.250.5  master.example.com master" >> /etc/hosts
echo "192.168.250.10 client.example.com client" >> /etc/hosts
#echo 'supercede domain-name "example.com";' > /etc/dhcp/dhclient.conf
#sed -i '/search/ d;$ a\search example.com' /etc/resolv.conf
#sed -ri 's/^[#\s]*(UseDNS)\s+yes.*/\1 no/' /etc/ssh/sshd_config
#service sshd restart
exit 0
END

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/centos-6.6-64-nocm"
  #config.vm.box = "puppetlabs/centos-7.0-64-nocm"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  # Default client
  config.vm.define "client", primary: true do |client|
    client.vm.hostname = "client.example.com"
    client.vm.network :private_network, ip: "192.168.250.10"
    client.vm.provision "shell", inline: $setupscript
  end

  # A puppetmaster
  config.vm.define "master", autostart: false do |puppetmaster|
    puppetmaster.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    puppetmaster.vm.hostname = "master.example.com"
    puppetmaster.vm.network :private_network, ip: "192.168.250.5"
    puppetmaster.vm.provision "shell", inline: $setupscript
  end

  ## Puppet Server
  #config.vm.define "puppetserver", autostart: false do |puppetserver|
  #  puppetserver.vm.hostname = "puppet-server.example.com"
  #  puppetserver.vm.network :private_network, ip: "192.168.250.6"
  #  puppetserver.vm.provision "shell", inline: $setupscript
  #  puppetserver.vm.provider :virtualbox do |ps|
  #    ps.memory = 1024
  #  end
  #end
end
